version: 2
updates:

  # Maintain dependencies for this gradle project
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      groups:
        logback:
          patterns:
            - "ch.qos.logback"
        eclipse-collections:
          patterns:
            - "org.eclipse.collections"
        glassfish:
          patterns:
            - "org.glassfish.jaxb"
        junit:
          patterns:
            - "org.junit.vintage"
            - "org.junit.jupiter"
            - "junit"


  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: auto
    schedule:
      interval: daily
