# Automatically updates Gradle wrapper to the latest version
# Runs weekly on Sunday at midnight UTC
# Creates PR if updates are available
name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
