name: Gradle wrapper validation

on:
  push:
    branches:
      - '*'

jobs:
  validation:
    runs-on: ubuntu-latest
    name: on ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
