name: jdeprscan

on:
  workflow_dispatch:
    types: jdeprscan

jobs:
  jdeps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Copy dependency jar files to libs folder
        run: ./gradlew copyDependenciesToLibs
      - name: Create jar file for project
        run: ./gradlew assemble
      - name: Run jdeprscan task
        run: jdeprscan --for-removal --verbose --class-path libs/*.jar build/libs/java_playground.jar
