# Scans Java code for deprecated API usage that's marked for removal
# Helps identify code that will break in future Java versions
# Runs manually via workflow_dispatch
name: jdeprscan

on:
  workflow_dispatch:

jobs:
  jdeps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Copy dependency jar files to libs folder
        run: ./gradlew copyDependenciesToLibs
      - name: Create jar file for project
        run: ./gradlew assemble
      - name: Run jdeprscan task
        run: jdeprscan --for-removal --verbose --class-path libs/*.jar build/libs/java_playground.jar
