name: Run tests2

on:
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        - uses: actions/upload-artifact@v2
          with:
            name: pr_number
            path: pr/
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
